### ISSUE TITLE
[Memory Leaks] Invert relationship between `Result` and `FastBootInfo`

### ISSUE THREAD

**Issue by arjansingh** [ember-fastboot/fastboot#103]
@kratiahuja [mentioned](https://github.com/ember-fastboot/fastboot/pull/100#discussion_r90723402) that we might be able to reduce memory leakage by injecting the `Result` object as a global rather than just the `FastBootInfo` object. I think she might have a good point.

That would involve inverting the current relationship between `FastBootInfo` and `Result` so it's not a trivial refactor, but it's doable.

**Comment by kratiahuja** [comment]
Also currently the `result` object will not work in a concurrent request environment. The reason being currently only upto the app instance boot everything is synchronous. Once the `instance.visit` starts, there is no guarantee of requests being run in serial order (ie when you fetch API data, they are all asynchronous). Having a global `result` object is wrong in these environments.

**Comment by kratiahuja** [comment]
This can be closed @arjansingh
