### ISSUE TITLE
Drop support for Node 0.12?

### ISSUE THREAD

**Issue by kratiahuja** [ember-fastboot/fastboot#106]
Given that Node 0.12 is not longer LTS, should we officially drop support for this in FastBoot? I believe `ember-cli` dropped support for it. We also probably need to make an annoucement for the same so that users are not unhappy.

**Comment by rwjblue** [comment]
Yes, node 0.12 is dead!

**Comment by kellyselden** [comment]
It's interesting that every addon is going to have to choose when to go node 4 and stop supporting older ember-cli releases... Maybe the ember-cli team should include in our node 0.12 drop announcement a note about addons, and suggest "don't expect new releases of addons from this day forward to support node 0.12"?

**Comment by rwjblue** [comment]
Well, dropping 0.12 here doesn't mean we don't support older ember-cli versions, just that we don't support older Nodes. 

I would need to reread the blog post stating our support, but I am under the impression that it already applied "ecosystem wide".

**Comment by kellyselden** [comment]
> Well, dropping 0.12 here doesn't mean we don't support older ember-cli versions, just that we don't support older Nodes.

Ah yes, my mistake. Not as big an issue then.

**Comment by stefanpenner** [comment]
🔥

**Comment by jasonmit** [comment]
Would dropping support require a major bump?  Unsure how to go about this as I also drop <= 0.12 support in some addons.  My gut says it might, but I don't really know...

**Comment by rwjblue** [comment]
It will not be a major bump for ember-cli for certain, our SemVer guarantee specifically is that we will support "currently supported/maintained Node LTS versions" and therefore no major bump is required (since this is not a breaking change from that perspective).

**Comment by kratiahuja** [comment]
This is fixed and dropped now.
