### ISSUE TITLE
borrow eslint rules from ember-cli (good for new contributors)

### ISSUE THREAD

**Issue by kellyselden** [ember-fastboot/fastboot#109]
Suggested here https://github.com/ember-fastboot/fastboot/pull/108#issuecomment-271263783

We could use linting from eslint using ember-cli's rules as a baseline. This is great for new contributors because you don't need to know fastboot code is working, but updating the code the match the rules will get you some exposure.

**Comment by samtsai** [comment]
@kellyselden I'll take a stab at this :)

**Comment by samtsai** [comment]
Ready for review @kellyselden @rwjblue

**Comment by mehulkar** [comment]
This was done by @kratiahuja in #210. Can close this!
