### ISSUE TITLE
header splitting on ', ' corrupts some headers

### ISSUE THREAD

**Issue by kellyselden** [ember-fastboot/fastboot#111]
Can someone explain the header splitting here? https://github.com/ember-fastboot/fastboot/blob/b62e795c8c21c4a5dca09f2cf20e4367c843fc7b/src/fastboot-headers.js#L8

`this.headers[header] = headers[header].split(', ');`

I noticed that it destroys the user agent in the header. Turns

`'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36'`

into

```js
[
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML',
  'like Gecko) Chrome/55.0.2883.95 Safari/537.36'
]
```

which causes me to need this code in Ember:

```js
        let headers = get(this, 'fastboot.request.headers');
        let userAgent = headers.get('user-agent');

        if (userAgent instanceof Array) {
            userAgent = userAgent.join(', ');
        }
```

**Comment by danmcclain** [comment]
Express combines multiple values into a comma separated list, where as the `Header` spec returns an array of values

**Comment by kellyselden** [comment]
> Express combines multiple values into a comma separated list

@danmcclain I'm curious where you determined that? While I was stepping through express header building, I saw it build an array when dealing with multiple values: https://github.com/ember-fastboot/fastboot/pull/84#issuecomment-272041468

**Comment by danmcclain** [comment]
I don't remember now, I just remember hitting it before, that was why I added that code, I'd be super happy if that was not the case.

**Comment by rwjblue** [comment]
closed by https://github.com/ember-fastboot/fastboot/pull/113
