### ISSUE TITLE
children elements are rendered outside of parent

### ISSUE THREAD

**Issue by MartinMalinda** [ember-fastboot/fastboot#130]
In the new ember-api-docs, there is this template:

```handlebars
<p class="attributes">
    {{#if model.extends}}
      <div class="attribute">
     ...
      </div>
    {{/if}}
    {{#if model.uses}}
      <div class="attribute">
     ...
      </div>
    {{/if}}
    {{#if model.file}}
      <div class="attribute">
       ...
      </div>
    {{/if}}
    {{#if model.module}}
      <div class="attribute">
       ...
      </div>
    {{/if}}
  </p>
```

Fastbooot renders the `.attribute` outside the `.attributes`. On client side render it is OK.

Server side render (incorrect)
![screen shot 2017-03-17 at 21 10 54](https://cloud.githubusercontent.com/assets/9468793/24061093/55e58a4a-0b56-11e7-8a11-05cfb8900338.png)
Client side render (correct)
![screen shot 2017-03-17 at 21 10 43](https://cloud.githubusercontent.com/assets/9468793/24061096/59bff20e-0b56-11e7-8afe-8c88ebf84300.png)

Changing the tag name of `.attributes` from `p` to `div` solved the issue there: https://github.com/ember-learn/ember-api-docs/pull/162/files

**Comment by topaxi** [comment]
`<p>` should only contain phrasing content, `<div>`s aren't so they move outside of the `<p>` elements. This correct behavior is according to the html5 spec.

https://developer.mozilla.org/en/docs/Web/HTML/Element/p

If you inspect code in your DevTools the same should happen.

I don't think this is a Fastboot bug.

**Comment by MartinMalinda** [comment]
@topaxi makes sense, thank you for the explanation. I was not familiar with this.
