### ISSUE TITLE
Unused dependency triggers warning about Regular Expression DoS vulnerability

### ISSUE THREAD

**Issue by rogatty** [ember-fastboot/fastboot#132]
https://snyk.io/test/github/ember-fastboot/fastboot shows that FastBoot is vulnerable to a ReDoS attack. FastBoot depends on [glob@^4.0.5](https://github.com/ember-fastboot/fastboot/blob/20b687d87d41547e08b35aceff473dc92b7b2570/package.json#L35) which depends on [minimatch@^2.0.1](https://github.com/isaacs/node-glob/blob/v4.5.3/package.json#L22) which is vulnerable. More details about the vulnerability: https://snyk.io/vuln/npm:minimatch:20160620

glob should be updated to at least v7.1.1 where [the issue was fixed](https://github.com/isaacs/node-glob/commit/f0f0872b660d83b1986cd1dd16ec4808fa183adc).

**Comment by kratiahuja** [comment]
Is FastBoot using (requiring) `glob` anywhere? [Seems like it is a dead dependency](https://github.com/ember-fastboot/fastboot/search?utf8=%E2%9C%93&q=glob&type=). But I could be wrong.

**Comment by rogatty** [comment]
You're right, it was introduced in [the first commit](https://github.com/ember-fastboot/fastboot/commit/7829d37194282a30b61455aa6474b4d73745e1ac#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R31) and not used at all. It should be easy fix, then :smile:

**Comment by danmcclain** [comment]
It would be best in the future to follow the [Security guidelines](https://emberjs.com/security/) in the future to minimize exposure. Thanks for the issue still!
