### ISSUE TITLE
Cannot affect root <html> element

### ISSUE THREAD

**Issue by eshtadc** [ember-fastboot/fastboot#152]
It appears that you can update the body or head to be rendered by FastBoot, but even if you have added attributes to the documentElement (<html> tag) that they are ignored.  If I am reading the code correctly the html is just the template html file from the ember app, head, and body are serialized from simpledom (but not `documentElement`).

https://github.com/ember-fastboot/fastboot/blob/master/src/result.js#L128
```
function insertIntoIndexHTML(html, head, body) {
  if (!html) { return Promise.resolve(html); }

  if (body) {
    let isBodyReplaced = false;
    html = html.replace("<!-- EMBER_CLI_FASTBOOT_BODY -->", function() {
      isBodyReplaced = true;
      return body;
    });

    if (!isBodyReplaced) {
      return missingTag('<!--EMBER_CLI_FASTBOTT_BODY-->');
    }
  }

  if (head) {
    let isHeadReplaced = false;
    html = html.replace("<!-- EMBER_CLI_FASTBOOT_HEAD -->", function() {
      isHeadReplaced = true;
      return head;
    });

    if (!isHeadReplaced) {
      return missingTag('<!--EMBER_CLI_FASTBOTT_HEAD-->');
    }
  }

  return Promise.resolve(html);
}
```

Is this by design or could this be something to work on?  It would address the following:
https://github.com/ember-fastboot/ember-cli-fastboot/issues/331

**Comment by rwjblue** [comment]
This is now possible (added by #180 ) and released in 1.2.0.
