### ISSUE TITLE
FastbootHeaders.get trolled me hard.

### ISSUE THREAD

**Issue by cibernox** [ember-fastboot/fastboot#172]
This is me whining, but I thought that if I got trolled so hard by such a subtle thing, other might be and it could be a way of mitigating it.

A coworker of mine made this change in an ember-data adapter:

```diff
          // Check that the returned data is of the expected format
 -        let headers = this.get('fastboot.request.headers');
 -        let contentType = headers.get('Content-Type');
 +        let headers = get(this, 'fastboot.request.headers');
 +        let contentType = get(headers, 'Content-Type');
```

By all means this seemed like a very reasonable code, it passed the review and got merged.

However, despite of what its so engrained in the mind of any Ember developer, `headers.get(key)` and `get(headers, key)` are not equivalent in this context.
See https://github.com/ember-fastboot/fastboot/blob/bb63049c5e529b9af4794ec1b0e592b7f32a47f8/src/fastboot-headers.js#L52-L54

If there is a way we could prevent other developers to pull their hair, I'd be happy to help

**Comment by danmcclain** [comment]
As the implementer of this hair pulling feature, my goal was to match the [Headers API](https://developer.mozilla.org/en-US/docs/Web/API/Headers) that exists in browser for the fetch API. Adding context for the design decision, not trying to dismiss your comment

**Comment by cibernox** [comment]
And I understand the reasoning, I don't think it's wrong design. But the boundary where we are in EmberObject-land and in PlanJS-land got fuzzy. I was thinking that perhaps there is some special symbol or something objects can implement to cuac like an EmberObject when used with `Ember.get`

**Comment by rwjblue** [comment]
We can implement `unknownProperty` to detect the `get(headers, 'Content-Type')`  do the right thing (optionally with a warning?)...

**Comment by cibernox** [comment]
How would that be? add an `unknownProperty() { }` function to the class?

**Comment by rwjblue** [comment]
Yes
