### ISSUE TITLE
Allow chunked transfer encoding

### ISSUE THREAD

**Issue by marcoow** [ember-fastboot/fastboot#174]
I've been looking into ways to easily get chunked transfer encoding with FastBoot, the main motivation being that I'd like to have a mechanism where big shoeboxes don't unnecessarily delay initial rendering of the page.

I believe a really easy way to get this should be to send the response in 3 chunks:

* everything until `</head>`
* everything until the first shoebox if present (or the complete rest of the document if not)
* the shoebox(es) if present and the final `</body></html>`

Of course being able to send chunks of the document as it is rendered on the server side would be ideal but I guess that's a bigger change in the FastBoot internals so the above solution might be a good start?

I looked at the code and I guess it should be straight forward to add a `chunks()` method (or so) to https://github.com/ember-fastboot/fastboot/blob/master/src/result.js and modify https://github.com/ember-fastboot/fastboot-express-middleware so that it writes each of the chunks instead of the complete HTML at once but I wanted to get some feedback before creating a PR.

**Comment by topaxi** [comment]
With addons like [ember-cli-head](https://github.com/ronco/ember-cli-head) this might be problematic I guess? As `<head>` might be re-rendered after route transitions.

**Comment by marcoow** [comment]
I think the `Result` class is only used once `visit` has resolved at which time the Ember app should not be able to change anything anymore.

**Comment by rwjblue** [comment]
To be clear, this issue is not about streaming responses (which has a number of issues as well). I think generally speaking the suggested changes here are a good idea...

**Comment by kratiahuja** [comment]
Isn't shoebox already created when `visit` is done? How is it going to be beneficial to send shoebox responses in chunks?

**Comment by marcoow** [comment]
Right, this issue is mostly about sending the main doc and the shoebox in 2 chunks after `visit` has resolved and the response has been rendered so that large shoeboxes don’t block rendering. The problem Joanie that if you have a 1MB shoebox, all of that 1MB has to be downloaded before the page can be rendered while if the main doc and the shoebox are sent in 2 chunks, the browser can render the page while downloading the huge shoebox. This makes using the shoebox Wayne’s costly.

**Comment by kratiahuja** [comment]
Oho I see what you mean now. Yeah this totally makes sense to me. The suggested changes seem good to me provided they are an opt-in.
