### ISSUE TITLE
FastBoot behind a reverse proxy

### ISSUE THREAD

**Issue by lucacorti** [ember-fastboot/fastboot#184]
When deployed behind a reverse proxy, `FastBoot` does not honour the `X-Forwarded-Host` header. `FastBootRequest` always tries to match the `Host` header from the request with the `hostWhitelist` configuration.

https://github.com/ember-fastboot/fastboot/blob/3b752ffbac7565edd57239b9640f058d0718dcf9/src/fastboot-request.js#L25

This breaks deploying in reverse proxy scenarios. My current workaround is to set request.headers.host from `fastboot-app-server`:

```
const httpServer = new ExpressHTTPServer();
const app = httpServer.app;

app.use(function(req, res, next) {
  const xForwardedHost = req.headers['x-forwarded-host'];
  if(xForwardedHost && xForwardedHost.length) {
    req.headers['host'] = xForwardedHost;
  }
  next();
});

const server = new FastBootAppServer({
  distPath: path.resolve(process.cwd(), 'dist'),
  httpServer
});

server.start();
```

**Comment by seanabrahams** [comment]
Just ran into this myself and your solution works. Thank you 👍
