### ISSUE TITLE
Should there be a default for `destroyAppInstanceTimer`?

### ISSUE THREAD

**Issue by nlfurniss** [ember-fastboot/fastboot#186]
I'm investigating an [issue with ember-fetch](https://github.com/ember-cli/ember-fetch/issues/106) where ember-fetch, Ember 3.1-beta, and fastboot are causing the server to hang.

I know this is an option that can be specified, but is it worth setting a default timer, like 5-10 seconds?

**Comment by kratiahuja** [comment]
Setting a default means we may also kill a valid request which not the intention. Every app and deployment may be different so setting a default value would be a bad idea IMO.

**Comment by nlfurniss** [comment]
K, sounds good
