### ISSUE TITLE
Module unification: rendering within partials give fastboot errors

### ISSUE THREAD

**Issue by izelnakri** [ember-fastboot/fastboot#191]
Im currently running fastboot on module unification. And it works generally well. However I noticed rendering issues when it comes to using partials in templates.

If in `routes/index/template.hbs` I use

```hbs
<h1>Hello world</h1>
```
it gets rendered

however if I use a partial, partial contents dont get rendered in the fastboot generated output:
```hbs
{{partial "homepage"}}
```

This doesnt get rendered on the server side. It does get rendered afterwards when app takes over.

The error message I get is:
TypeError: parent.insertAdjacentHTML is not a function
    at _insertHTMLBefore (/Users/izelnakri/myapp/frontend/tmp/assets/vendor.js:17384:20)

I suspect this could be due to container registration/lookups which are completely different with the module unification/new ember-resolver. 

Previously my partial declarations were different too, pre-module unification it was {{partial "partials/homepage"}} now it is {{partial "homepage"}}. I like the new one better, but this could also be the cause.

**Comment by rwjblue** [comment]
What Ember version? What are the contents of the partial? Where on disk is the partial? Can you provide a reproduction?

**Comment by izelnakri** [comment]
"ember-source": "3.2.2".

Partial holds:
- Static html
- one complex component which uses services as state, (it gets server side rendered correctly when used outside of the partial). 
- One translation helper({{t "something"}}). 
- One {{link-to ""}}

partial is under `src/ui/partials/homepage.hbs`.

**Comment by kratiahuja** [comment]
Is this a FastBoot issue or Ember/Glimmer issue?

**Comment by zeppelin** [comment]
@rwjblue @izelnakri I have the same issue after upgrading from `3.7` to `3.8`. Receiving when `SafeString` is rendered by the Glimmer VM.

**Comment by williamweckl** [comment]
It happens with helpers too either without module unification.

```
"ember-source": "3.10.0",
"ember-cli-fastboot": "2.1.1"
```

I have a simple helper that works without fastboot but raises `TypeError: parent.insertAdjacentHTML is not a function` at fastboot:
```
import { helper } from '@ember/component/helper';
import { htmlSafe } from '@ember/template';

export function worldFlag(params/*, hash*/) {
  let country = params[0];
  let size = params[1];

  const result = `<i class="flag${size} flag-${country.toLowerCase()}"></i>`;
  return htmlSafe(result);
}

export default helper(worldFlag);
```

**Comment by izelnakri** [comment]
Since partials are deprecated Im closing this issue.
