### ISSUE TITLE
Disabling Fastboot during deploy

### ISSUE THREAD

**Issue by midhunpm** [ember-fastboot/fastboot#216]
Hi,
We have an ember application which is deployed as two separate application based on certain scenarios. We pass few environment variables during build time to differentiate the two applications in the code.
Our problems is that one application is running on Fastboot and we are pre-rendering the pages using ember-prember. The other application is supposed to be run as a normal ember app without Fastboot or server-side rendering.
How can we achieve this with the same code base?
During development, we are using 'FASTBOOT_DISABLED=true ember s' to disable Fastboot. But when we deploy this to stage or production environment (buildEnv=production) the FASTBOOT_DISABLED=true doesn't work. 
Any suggestions?
Thanks!

**Comment by CvX** [comment]
It depends on how your ember app is run in production.

The `FASTBOOT_DISABLED` flag is an option of [ember-cli-fastboot](https://github.com/ember-fastboot/ember-cli-fastboot), and it probably would work in production environment, but usually production apps aren't run with `ember s`.

So, if you use for example [fastboot-app-server](https://github.com/ember-fastboot/fastboot-app-server), you could conditionally route the request to either fastboot or a static file. Something like this:

```js
// server.js

const FastBootAppServer = require('fastboot-app-server');
const express = require('express');
const path = require('path');

const server = new FastBootAppServer({
  beforeMiddleware(app) {
    if (process.env.FASTBOOT_DISABLED) {
      // Serve the static assets
      app.use(express.static('dist'));

      // Return the index for any other path
      app.get('/*', (req, res) => {
        res.sendFile(path.join(__dirname, 'dist', 'index.html'));
      });
    }
  },
});

server.start();
```
