### ISSUE TITLE
Accomodate changes to the index without a server restart

### ISSUE THREAD

**Issue by habdelra** [ember-fastboot/fastboot#23]
since the index will generally point to fingerprinted assets, when i deploy updates to my ember application, the updated index will not be read by the fastboot server until i restart node. it would be really great if there was some way by which the fastboot server could detect a change to the index file on disk and re-read the index from disk--or if there was some means by which i could inform the fastboot server to re-read the index from disk (via redis or something?). or maybe fastboot could read the index from something like redis?

**Comment by jasonmit** [comment]
https://github.com/ember-fastboot/ember-fastboot-server/pull/20 would enable this sort of flexibility

**Comment by habdelra** [comment]
I've actually just created some middleware to do an ember-cli-deploy deploying the ember app to the fastboot server and restarting the internal ember application as part of the deployment: https://github.com/habdelra/ember-fastboot-deploy

**Comment by jasonmit** [comment]
Creative, I dig it :+1:

**Comment by habdelra** [comment]
big props to @tomdale, it's mostly his ideas, I just wrote the code

**Comment by tomdale** [comment]
We now support sending `SIGUSR1` to reload.
