### ISSUE TITLE
Drop `najax` global by default?

### ISSUE THREAD

**Issue by rwjblue** [ember-fastboot/fastboot#246]
As we continue work towards the next major version (will be v3.0.0), I'd like to seriously consider dropping `najax` from the default set of global properties added by this library.

The primary reasons are:

* Recent versions of ember-data (3.12+) will automatically use `ember-fetch` (or global `fetch`) if present, and does not need special logic around `najax`
* New applications (as of ember-cli@3.13.0) include `ember-fetch` by default, and do **not** include jQuery by default. Considering that `najax` is a `jQuery.ajax` emulation API, I think this library should avoid exposing it.
* `najax` (as a dependency of this library) is difficult for the host application to control (e.g. get their own version), and would be better if they provided it themselves (via `buildSandboxGlobals` API)
* Providing backwards compatibility is **very** easy (add `najax: require('najax')` via `buildSandboxGlobals`)
* It seems better to "follow a spec" (suggesting `fetch` usage)

Thoughts?

**Comment by ryanto** [comment]
👍 Sounds good.

`najax` is something that you eventually run into and have to learn when doing FastBoot work, it's not bad, but it is another thing you have to know.

Using fetch sounds like a great idea. I think that both fetch and node-fetch are pretty common tools in SSR and do a good job at providing API consistency. The fact that this all comes bundled up for us with ED + ember-fetch is awesome, so strongly in favor of this.

**Comment by rwjblue** [comment]
@sdhull 

For a long time ember-data itself only supported making jQuery requests, and since `najax` provides a nice "jQuery like" API it was a very convenient way to be able to move forward with SSR in general without having to rewrite all of the request logic in ember-data. Now that recent versions of ember-data will use `fetch` out of the box, the `najax` dependency / global is just hanging around for no good reason.

> I think if it truly is as easy as najax: require('najax') to fix apps that break as a result of this change (and that is well-documented), seems fine to me.

👍 awesome, thank you! I'll make sure it is well documented (in the release notes, in the README, and likely in other projects as we update them to `fastboot@3`).

**Comment by tomdale** [comment]
I think this has served it's purpose. :+1: on dropping.
