### ISSUE TITLE
Cannot wait for promises after model hooks

### ISSUE THREAD

**Issue by boris-petrov** [ember-fastboot/fastboot#274]
This is written in the documentation (and is true). However, even simple use-cases like [this one](https://github.com/boris-petrov/ember-fastboot-test) become impossible to fastbootify. Check out the repo. There is a component that is rendered conditionally (depending on the model) and in it I want to fetch more data and render it too. That's not possible right now. As you see from the console.log's - the component is rendered after all hooks that FastBoot gives us - so `deferRendering` doesn't work.

I'm not sure I'm doing something wrong or this is just not possible. But this is a trivial use-case, am I missing something?

**Comment by rwjblue** [comment]
Well, its definitely possible in general, it is just annoying to do :smile:

For example, you could extract the data loading to a shared function and have it invoked by the route when in fastboot. I agree, this doesn't feel like a great solution though, and we should work on a better overall solution.

**Comment by boris-petrov** [comment]
Well, on the contrary, it's not possible to do in general. You could imagine a use-case where the model hook calls a backend API which returns either `true` or `false`. Depending on that, the app renders component `A` or component `B`. Component `A` will request backend API `api/A` and component `B` will request backend API `api/B`. How do you that with Fastboot?

You *could* potentially load both backend APIs in the model hook... but what happens if they have side-effects? That's just plain wrong.

Either I am misunderstanding something or this is just not possible to do "right" in Fastboot.

**Comment by scottmessinger** [comment]
Here's a blog post on how we do it: 

https://dev.to/scottamesmessinger/defer-rending-of-component-data-loading-with-fastboot-and-ember-js-53p1

In short, we call `this.fastboot.deferRendering(promise)` and pass it a promise we wait to resolve until all our requests are finished.

**Comment by xg-wang** [comment]
Maybe we can propose a more intuitive API, but for now ^^ is the way to go
