### ISSUE TITLE
Quickstart is not working

### ISSUE THREAD

**Issue by jathanasiou** [ember-fastboot/fastboot#275]
Following the exact instructions under https://www.ember-fastboot.com/quickstart I created an app and added `ember-cli-fastboot`. After restarting I had added an index route to confirm:

```bash
$ ember new github-fastboot-example
$ ember generate route index
$ ember install ember-cli-fastboot
$ ember s --port 8081
```

```js
import Route from '@ember/routing/route';
import { inject as service } from '@ember/service';

export default Route.extend({
	fastboot: service(),
  
  model() {
  	console.log('this.fastboot.isFastBoot', this.fastboot.isFastBoot);
    // prints
    // this.fastboot.isFastBoot false
    // in browser console
    return { prop: 123 }
  }
});
```

Am doing something obvious wrong or is the Quickstart guide missing a step?

**Comment by rwjblue** [comment]
`this.fastboot.isFastBoot` will **always** be false in the browser, `.isFastBoot` is true when ran _in the server_ (the browser is **not** in a FastBoot context).

**Comment by kiwiupover** [comment]
@jathanasiou is you are using [vscode](https://code.visualstudio.com/download) go to the package.json file and click the debug button just above the scripts then select se

![https://share.getcloudapp.com/9ZujpwOL](https://share.getcloudapp.com/9ZujpwOL)

**Comment by xg-wang** [comment]
Potentially something to improve as part of doc improvements, closing.
