### ISSUE TITLE
/snapshots directory is included and balloons the package size

### ISSUE THREAD

**Issue by burritoIand** [ember-fastboot/fastboot#280]
When switching from 3.0.2 to 3.1.0 I noticed that the folder size for node_modules/fastboot increased substantially.

After looking into it with @rwjblue we found that it was the /snapshots directory accidentally being included.

```
ls -al snapshots/
total 65264
drwxr-xr-x   6 eric  staff   192B Oct 26 13:12 ./
drwxr-xr-x  15 eric  staff   480B Oct 26 13:12 ../
-rw-r--r--   1 eric  staff   7.9M Oct 26  1985 0-setup.heapsnapshot
-rw-r--r--   1 eric  staff   8.1M Oct 26  1985 1-first-visit.heapsnapshot
-rw-r--r--   1 eric  staff   7.9M Oct 26  1985 2-second-visit.heapsnapshot
-rw-r--r--   1 eric  staff   7.9M Oct 26  1985 3-third-visit.heapsnapshot
```

**Comment by rwjblue** [comment]
Thanks for reporting! I'll try to fix and re-release. Sorry for the trouble.

**Comment by burritoIand** [comment]
not a prob! I only noticed because like I mentioned, lambda@edge has a max compressed size limit for origin-requests of 50MB, and after upgrading to 3.1.0 it suddenly hit that limit which caused me to investigate.
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-limits.html#limits-lambda-at-edge

Thanks for the update!
