### ISSUE TITLE
document.title should take precedence over the <head> HTML

### ISSUE THREAD

**Issue by buschtoens** [ember-fastboot/fastboot#32]
Relevant code from [`ember-fastboot-server`](https://github.com/ember-fastboot/ember-fastboot-server/blob/a47e8d22f587ebe7281d989d0dcd92e12ff82b96/lib/server.js#L58-L69):

```js
FastBootServer.prototype.insertIntoIndexHTML = function(title, body, head) {
  var html = this.html.replace("<!-- EMBER_CLI_FASTBOOT_BODY -->", body);

  if (title) {
    html = html.replace("<!-- EMBER_CLI_FASTBOOT_TITLE -->", "<title>" + title + "</title>");
  }
  if (head) {
    html = html.replace("<!-- EMBER_CLI_FASTBOOT_HEAD -->", head);
  }

  return html;
};
```

If I am not missing something, a title set by `document.title` would be overridden by the more "general" `<head>` tag. Shouldn't this order be reversed or am I missing something?

If so, I'll make a PR.

**Comment by tomdale** [comment]
We have resolved the tension here by no longer supporting `document.title`, since which one took precedence was confusing and different people wanted different behavior. Please use the `ember-cli-head` instead. 🤗
