### ISSUE TITLE
Double <title> in served pages

### ISSUE THREAD

**Issue by jeffplang** [ember-fastboot/fastboot#33]
Rendered HTML inserted into `index.html` via [`insertIntoIndexHTML`](https://github.com/ember-fastboot/ember-fastboot-server/blob/a47e8d22f587ebe7281d989d0dcd92e12ff82b96/lib/server.js#L58-L69) creates a second `<title>` tag, the first being the generic `<title>APP_NAME</title>`

**Comment by danmcclain** [comment]
@jeffplang in what case? Do you have a title tag existing in your `index.html`?

**Comment by rwjblue** [comment]
@danmcclain ember-cli blueprint includes a title tag.  I think we should remove it...

**Comment by danmcclain** [comment]
@rwjblue Confirm, I just wanted to confirm that the generated `index.html` was the source of the first title tag, not dueling `doc.title` and something like `ember-cli-head`

**Comment by xg-wang** [comment]
I think this is fixed
