### ISSUE TITLE
Install fails on Windows

### ISSUE THREAD

**Issue by vlascik** [ember-fastboot/fastboot#40]
`ember install ember-cli-fastboot` fails because of ember-fastboot-server postInstall script on Windows
```
npm ERR! ember-fastboot-server@0.5.4 postinstall: `scripts/is-not-legacy-vm || npm install contextify@^0.1.11`
npm ERR! Exit status 1
`scripts/is-not-legacy-vm || npm install contextify@^0.1.11`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ember-fastboot-server@0.5.4 postinstall script 'scripts/is-not-legacy-vm || npm install contextify@^0.1.11'.
```
`scripts/is-not-legacy-vm` won't run just by using `#!/usr/bin/env node` as first line of `scripts/is-not-legacy-vm` on Windows, so it tries to include contextify, which is not needed on recent node anyway, and requiring it is a kind of PITA because of prerequisites like specific version of Visual Studio installed. Changing postInstall to `node scripts/is-not-legacy-vm || npm install contextify@^0.1.11` works on Windows, but perhaps something more universal would be a better idea.

**Comment by bmeurant** [comment]
This is related to  ember-fastboot/ember-cli-fastboot#176. Isn't it ?

0.6.2 did not yet bump ember-fastboot-server version and does not work. Awaiting the next release you can install the master version : 

`ember install https://github.com/ember-fastboot/ember-cli-fastboot.git`

**Comment by tomdale** [comment]
We're cutting the first beta today, which will include this fix. :)

**Comment by bmeurant** [comment]
Nice ! Thx

**Comment by tomdale** [comment]
This should be fixed now; let me know if it's not.

**Comment by bmeurant** [comment]
It works well locally, thx ! 

But I have now issues deploying on heroku. Probably related to heroku/heroku-buildpack-emberjs#6 ?
