### ISSUE TITLE
Deprecate doc.title?

### ISSUE THREAD

**Issue by danmcclain** [ember-fastboot/fastboot#51]
`doc.title` was implemented pre `ember-cli-head`. Since we are pre-1.0, I think we should consider deprecating `doc.title` in favor of `ember-cli-head`.

**Comment by arjansingh** [comment]
I was wondering that myself. Shouldn't it just be a part of the `<head>` content?

**Comment by danmcclain** [comment]
I'm going to PR when I get a chance

**Comment by tomdale** [comment]
This was done.
