### ISSUE TITLE
Add support for rootURL

### ISSUE THREAD

**Issue by thorsteinsson** [ember-fastboot/fastboot#53]
When using rootURL on the router, FastBoot completely ignores it and runs the app with the default rootURL `/`.

```
const Router = Ember.Router.extend({
  rootURL: '/en/'
});
```

Here's a repo to test it: https://github.com/thorsteinsson/ember-fastboot-rooturl

**Comment by esistgut** [comment]
I have the same issue for the same use case, FastBoot is ignoring my
```javascript
  let router = appInstance.lookup('router:main');
  router.rootURL = `/${language}/`;
```
inside an instance initializer.

**Comment by fivetanley** [comment]
Is this also generated in links, or are you just expecting a redirect when you visit `/`?

**Comment by esistgut** [comment]
Changing the rootURL makes all the links change as well. I'm doing this to "mount" my routes to the correct language prefix and to have different URLs for different languages.

**Comment by jasonmit** [comment]
> are you just expecting a redirect when you visit /?

I wouldn't expect it to redirect, but to assert like the router currently does that the requested URL starts with /en/.

> Is this also generated in links

It doesn't.

`curl http://localhost:3000/en/`
```
<!-- trimmed the output -->
<a id="ember995" href="/test" class="ember-view">test</a>
```

client-side http://localhost:4200/en/
```
<!-- trimmed the output -->
<a id="ember995" href="/en/test" class="ember-view">test</a>
```

**Comment by sebastianseilund** [comment]
I can confirm that FastBoot doesn't work when `rootURL` is set. The two issues described by @jasonmit are the causes:

> - rootURL isn't respected when the visit API handles the url
> - location is set to none in fastboot land which doesn't respect rootURL when used to generate urls (link-tos)

I got it working (using extreme monkey patching) by adding the [code from this Gist](https://gist.github.com/sebastianseilund/cd986e494628ce986d4e08e7b5c64191) into `app/instance-initializers/fastboot-fix.js`.

**Comment by tomdale** [comment]
Sounds like a bug in the `NoneLocation`; let's fix it in Ember itself.

**Comment by sebastianseilund** [comment]
I think you can close this one and track the issue in https://github.com/emberjs/ember.js/issues/13464.

**Comment by jasonmit** [comment]
I released a tiny addon to unblock, `ember install ember-fastboot-rooturl-patch` while we wait for the fix to land in stable.
