### ISSUE TITLE
Problems starting ember fastboot server

### ISSUE THREAD

**Issue by teckays** [ember-fastboot/fastboot#6]
I have tried running fastboot server both from command line and as a middleware and both of them failed

As command
`ember-fastboot  --port 4301 --app-file app/app.js --vendor-file dist/assets/vendor.js --html-file app/index.html`
throws an error: `cannot find module '/Users/<username>/apps/myApp/--port'`

As middleware:
``` lang-js
var server = new FastBootServer({
  appFile: path.join(root, 'app/app.js'),
  vendorFile: path.join(root, 'dist/assets/vendor.js'),
  htmlFile: path.join(root, 'app/index.html'),
  ui: ''
});
```
(What should be the `ui` variable set to? didn't find it readme)

throws this error: `Cannot read property 'userAgent' of undefined`

any help?

**Comment by teckays** [comment]
**UPDATE**
I've tried using `ember-cli-fastboot` same error:

`$ ember fastboot --serve-assets`
```
Cannot read property 'userAgent' of undefined
TypeError: Cannot read property 'userAgent' of undefined
    at Object.125.global/document (<anonymous>:121923:53)
    at s (<anonymous>:104896:621)
    at <anonymous>:104896:672
    at Object.106../big-play-button.js (<anonymous>:113849:23)
    at s (<anonymous>:104896:621)
    at <anonymous>:104896:672
    at Object.139.../../src/js/utils/merge-options.js (<anonymous>:123824:15)
    at s (<anonymous>:104896:621)
    at e (<anonymous>:104896:792)
    at <anonymous>:104896:810
59:vidler andreistalbe$
```

**Comment by teckays** [comment]
**UPDATE 2**

OK, the error was cause by `video.js` component, the plugin is using `document` and `window` to extract different types of data from the browser, `userAgent` in this case, however, `fastboot` being server-side doesn't know about these instances. Is there a way to safely build these dependencies? Some of the components are totally intended for client side environment so they should be skipped somehow. Is there a way to make it work on the current version of `ember-fastboot-server`?

**Comment by jasonmit** [comment]
> Some of the components are totally intended for client side environment so they should be skipped somehow

You would need to guard against the navigator being available before accessing it since it doesn't look like the sandbox environment shims it.

https://github.com/ember-fastboot/ember-fastboot-server/blob/master/lib/ember-app.js#L71-L82

**Comment by teckays** [comment]
@jasonmit I can't think of a general solution that would solve this problem in particular and all others that may occur with other custom ember components. Ensuring `window.navigator` exists before it's tried to be accessed requires me to change this 3rd party library which leads to more errors down the road because the `userAgent` is used on bootstrap the component. Setting `window.navigator.userAgent` to a default value might do the trick rather than ensuring it exists. 

As a possible solution, can this be shimmed in the `createSandbox()`?

**Comment by tomdale** [comment]
Closing this for now; let's make sure we cover things like this in the upgrade guide.
