### ISSUE TITLE
Some parts of instance lifecycle should be executed in the sandbox context

### ISSUE THREAD

**Issue by kratiahuja** [ember-fastboot/fastboot#94]
Today, building app instance, booting app instance, visiting route, waiting for app on deferred promise and destroying the app instance are all done outside the context of the sandbox. 

Ideally we should do it in the context of the sandbox. This issue tracks that. For more info look at PR #93 .

cc: @arjansingh @rwjblue

**Comment by xg-wang** [comment]
Superceded by https://github.com/ember-fastboot/fastboot/issues/244
