### ISSUE TITLE
How to serve assets when running from command line?

### ISSUE THREAD

**Issue by quaertym** [ember-fastboot/fastboot#98]
It is not clear how to serve assets when the app is booted with the command:
```
$ ember-fastboot path/to/dist --port 3000
```

What is the suggested way to do this?

**Comment by danmcclain** [comment]
The website is outdated in that section, the ember-FastBoot command is deprecated. The 2 common choices are 1) run fastboot-app-server (which is the replacement to ember-fastboot) or 2) use the fastboot-express-middleware with your own custom express stack

We do need to update the section that still references ember-fastboot

**Comment by quaertym** [comment]
I see, I have managed to make it work with `fastboot-app-server`. Thank you.

**Comment by rwwagner90** [comment]
How do I serve my app with fastboot-app-server? I need to make it work like this does in heroku `ember-fastboot dist --serve-assets-from dist --port $PORT`
